data : 
  seed : 69
  size : 1000
  input_filepath : data/raw
  output_filepath : data/processed
model : 
  max_steps : 10
  learning_rate : 0.0005
  weight_decay : 0 
  seed : 69
  jit_mode_eval : False
  optim : adamw_hf


